### PR TITLE
update libs to latest: mach-glfw/main, vulkan-zig/master

### PR DESCRIPTION
**Pull request by genejo**
- [x] By selecting this checkbox, I agree to license my contributions to this project under the license(s) described in the LICENSE file, and I have the right to do so or have received permission to do so by an employer or client I am producing work for whom has this right.

### CODE REVIEW

**Comment by slimsag** [comment]
Wow, you rock, thanks!

Just to confirm, we don't need to update any of the application code for this to work? I was surprised by that :D

**Comment by genejo** [comment]
Oh, happy to do this! That's right, no code change needed if it's just to update the libs.

Initially I thought to go for smth like `ensureDependencySubmodule` as in mach-glfw, but for now this should do. (or ensuring dependencies are up to date isn't worth pursuing for this example?)

**Comment by genejo** [comment]
Ok, sorry about all the noise. It works - tested on Win10 and Mac OS 12.2.1. I wasn't cloning properly. Had to do this

`git clone --branch updatelibs --recurse-submodules https://github.com/genejo/mach-glfw-vulkan-example`

Then `zig build run` works. Such a killer feature for you to put effort to ensure this works on any platform, thank you!

**Comment by Hsad** [comment]
I got this working as well, though I needed to install shaderc on Arch first.  That error made me think I had installed something wrong, not sure if that's worth adding into the install instructions.  Thanks for getting this working again.

**Comment by slimsag** [comment]
@Hsad I'd love to have that in the README, would you be willing to send a PR to update it?

**Comment by slimsag** [comment]
Thanks again @genejo !

**Pull request merged**
